services:
  postgres-with-vector:
    image: pgvector/pgvector:pg15
    container_name: my-pgvector-15
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AgentPro       # 数据库名
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data   # 数据将保存在当前目录下的 pgdata 文件夹